---
title: 'INDIVIDUAL PROJECT #2'
author: "Ann Erika D. Gabales"
date: "2022-12-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library ('twitteR')
library ('dplyr')
library('ggplot2')
library('RColorBrewer')
library('rtweet')
library('tm')
library('plotly')
```

```{r }
CONSUMER_SECRET <- "4a9VMi8yUx9w3kmHlcH4HZCo28xrq8KB4Xp5CiQxUYThcHIGxY"
CONSUMER_KEY <- "L5UGjr9G9AqtLSNUOqHexrcwB"
ACCESS_SECRET <- "FURsl7iwSXu5PMCTz6I0xHpaOHmUwwo32EGZ8UjrtpMGZ"
ACCESS_TOKEN <- "1599531219519410176-meJwDRKsJh4NE5Lc8mOxoM8CRvBQsj"

#connect to twitter app
setup_twitter_oauth(consumer_key = CONSUMER_KEY,
                    consumer_secret = CONSUMER_SECRET,
                    access_token = ACCESS_TOKEN,
                    access_secret = ACCESS_SECRET)


#Extract 10000 tweets from Twitter using twitteR package including retweets.
trendTweets2 <- searchTwitter("#bts",
                             n = 10000,
                             maxID = NULL,
                             lang = "en",
                             since = "2022-12-14",
                             until = "2022-12-21",
                             retryOnRateLimit = 120)
trendTweets2
```

```{r }
#data frame
trendsRT <- twListToDF(trendTweets2)
View(trendsRT)

head(trendsRT, n= 5)
names(trendsRT)
class(trendsRT)
data_text <- head(trendsRT$text)[1:5]
data_text

save(trendsRT,file= "trendsRT.Rdata")
load(file= "trendsRT.Rdata")
```

```{r }
#Subset the retweets and the original tweets into a separate file
#original tweets (subset)
tweetOrigin <- trendsRT %>%
  select(screenName,text,created,statusSource,isRetweet) %>% 
  filter(isRetweet == "FALSE")
save(tweetOrigin, file = "tweetOrigin.Rdata")

#retweets (subset)
retweetOrigin <- trendsRT %>%
  select(screenName,text,created,statusSource,isRetweet) %>% 
  filter(isRetweet == "TRUE")
save(retweetOrigin, file = "retweetOrigin.Rdata")

#
tweetOrigin %>%  
  group_by(1) %>%  
  summarise(max = max(created), min = min(created))

tweet <- tweetOrigin %>%  mutate(Created_round1 = created %>% round(units = 'hours') %>% as.POSIXct())
tweet

min1 <- tweetOrigin %>% pull(created) %>% min()
min1 
max1 <- tweetOrigin %>% pull(created) %>% max()
max1

#
retweetOrigin %>%  
  group_by(1) %>%  
  summarise(max = max(created), min = min(created))

retweets <- retweetOrigin %>%  mutate(Created_round2 = created %>% round(units = 'hours') %>% as.POSIXct())
retweets

min2 <- retweetOrigin %>% pull(created) %>% min()
min2 
max2 <- retweetOrigin %>% pull(created) %>% max()
max2
```

```{r }
#Plot the retweets and the original tweets using bar graph in vertical manner.
#Include legends.

#original tweets (plot)
tweets <- ggplot(tweetOrigin, aes(x= created)) + geom_histogram(aes(fill = ..count..)) +
  theme(legend.position = "right") + xlab("Time") + ylab("Number of tweets") + 
  scale_fill_gradient(low = "mistyrose", high = "purple")

tweets %>% ggplotly()

#retweets (plot)
tweets2 <- ggplot(retweetOrigin, aes(x = created)) + geom_histogram(aes(fill = ..count..)) +
  theme(legend.position = "right") + xlab("Time") + ylab("Number of retweets") + 
  scale_fill_gradient(low = "purple", high = "cyan")

tweets2 %>% ggplotly()
```
